"use client";
import { useCallback, useEffect, useState } from "react";
import { DEFAULT_COMPETITION_RULES, type Competition, type CompetitionStatus } from "@/lib/competitions/types";
const iso=(offset:number)=>new Date(Date.now()+offset).toISOString().slice(0,16);
export function CompetitionAdmin({onNotice}:{onNotice:(message:string)=>void}){
 const [allowed,setAllowed]=useState<boolean|null>(null),[items,setItems]=useState<Competition[]>([]);const [form,setForm]=useState({title:"",description:"",registrationOpensAt:iso(0),startsAt:iso(86400000),endsAt:iso(8*86400000),rules:DEFAULT_COMPETITION_RULES});
 const refresh=useCallback(()=>fetch("/api/admin/competitions",{cache:"no-store"}).then(async r=>{setAllowed(r.ok);if(r.ok){const p=await r.json() as {competitions:Competition[]};setItems(p.competitions)}}),[]);
 useEffect(()=>{void refresh()},[refresh]);
 const save=async()=>{const r=await fetch("/api/admin/competitions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,registrationOpensAt:new Date(form.registrationOpensAt).toISOString(),startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString()})});const p=await r.json() as {error?:string};onNotice(p.error??"Competition draft saved.");await refresh()};
 const transition=async(id:string,status:CompetitionStatus)=>{const r=await fetch("/api/admin/competitions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"transition",id,status})});const p=await r.json() as {error?:string};onNotice(p.error??("Competition "+status+"."));await refresh()};
 if(allowed===null)return <section className="content-page page-width"><p>Checking owner access…</p></section>;if(!allowed)return <section className="content-page page-width"><div className="page-intro"><div><span className="eyebrow">Administration</span><h1>Owner access required.</h1><p>Sign in with an administrator account to use competition controls.</p></div></div></section>;
 return <section className="content-page page-width competition-admin"><div className="page-intro"><div><span className="eyebrow">Owner control</span><h1>Competition operations.</h1><p>Draft validated rules, publish registration, operate the ladder, and archive immutable results.</p></div></div><div className="admin-competition-grid"><form onSubmit={e=>{e.preventDefault();void save()}}><label>Title<input required minLength={3} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div><label>Registration opens<input type="datetime-local" value={form.registrationOpensAt} onChange={e=>setForm({...form,registrationOpensAt:e.target.value})}/></label><label>Starts<input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>Ends<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label></div><div><label>Round<select value={form.rules.roundSeconds} onChange={e=>setForm({...form,rules:{...form.rules,roundSeconds:Number(e.target.value) as 30|60|120}})}><option>30</option><option>60</option><option>120</option></select></label><label>Tick<input type="number" min="100" max="1000" value={form.rules.actionIntervalMs} onChange={e=>setForm({...form,rules:{...form.rules,actionIntervalMs:Number(e.target.value)}})}/></label><label>Match limit<input type="number" min="1" max="100" value={form.rules.matchLimit} onChange={e=>setForm({...form,rules:{...form.rules,matchLimit:Number(e.target.value)}})}/></label></div><button type="submit">Save draft</button></form><div className="admin-competition-list">{items.map(item=><article key={item.id}><span>{item.status}</span><strong>{item.title}</strong><small>Rules v{item.rulesVersion} · {new Date(item.startsAt).toLocaleDateString()}</small><div>{item.status==="draft"&&<button onClick={()=>void transition(item.id,"registration")}>Open registration</button>}{item.status==="registration"&&<button onClick={()=>void transition(item.id,"active")}>Start</button>}{item.status==="active"&&<button onClick={()=>void transition(item.id,"closed")}>Close</button>}{item.status==="closed"&&<button onClick={()=>void transition(item.id,"archived")}>Archive</button>}{!["cancelled","archived"].includes(item.status)&&<button className="secondary" onClick={()=>void transition(item.id,"cancelled")}>Cancel</button>}</div></article>)}</div></div></section>
}
